
= Docker

== Docker: un environment portable

* Problème courante : Environnements différents entre le poste du dév. et la production

* Solution: Utiliser Docker pour définir un environment portable

== Exercices avec Docker

* Dans link:{gitserver-url}[Gitea,window="_blank"], examinez le fichier `Dockerfile`
* Dans link:{devbox-url}[Devbox,window="_blank"], essayez les commandes suivante:


[source,bash,subs="attributes"]
----
## Construire uniquement l'environnement de build
docker build --build-arg HTTP_PROXY=http://10.0.4.2:3128/ \
    --build-arg HTTPS_PROXY=http://10.0.4.2:3128/  \
    -t demoapp:build -f Dockerfile.build ./

## Executer un container
mvn -v 
docker run --rm -ti -v $(pwd):/app --entrypoint="bash" demoapp:build
bash-4.4# ls -al /app
bash-4.4# mvn -v # Difference ?
----

== Agents avec Docker

* *But:* Usage de Docker pour faciliter la définition des environements de build
* Le mot clef `agent` permet d'exécuter les "stages" dans
un container Docker, depuis une "image Docker",
ou depuis un `Dockerfile` (recette maison d'image Docker)

== Exercice : Agent Docker

* Exécuter l'étape *Build* dans un containeur
basé sur le fichier `Dockerfile.build`

* Attention, le proxy doit être précisé à Jenkins. Comment passer le flag `--build-arg` dans le pipeline?
** _Indice :_ Documentation link:https://jenkins.io/doc/book/pipeline/syntax/#agent[Directive Agent sur jenkins.io]

* Attention, le proxy doit également être passé à Maven, qui ne sait pas lire la variable `HTTP_PROXY`
** _Indice :_ Documentation de Maven link:https://maven.apache.org/settings.html#Proxies[sur la configuration d'un proxy]
** _Indice :_ L'utilisateur par défaut dans `Dockerfile.build` est `root`. Son `HOME` est le dossier `/root`
** _Indice :_ Vous pouvez tester dans la devbox de manière interactive

== Solution : Agent Docker 1/3

Fichier `Jenkinsfile` :

[source,groovy,subs="attributes"]
----
include::{pipeline-solutions}/08-Jenkinsfile-dockerfile-agents[]
----

== Solution : Agent Docker 2/3

Fichier `settings.xml` :

[source,xml]
----
<settings>
    <proxies>
        <proxy>
            <id>httpproxy</id>
            <active>true</active>
            <protocol>http</protocol>
            <host>10.0.4.2</host>
            <port>3128</port>
            <nonProxyHosts>ensg.eu|localhost</nonProxyHosts>
        </proxy>
        <proxy>
            <id>httpsproxy</id>
            <active>true</active>
            <protocol>https</protocol>
            <host>10.0.4.2</host>
            <port>3128</port>
            <nonProxyHosts>ensg.eu|localhost</nonProxyHosts>
        </proxy>
    </proxies>
</settings>
----

== Solution : Agent Docker 3/3

[source,Dockerfile,subs="attributes"]
----
FROM maven:3-jdk-8-alpine
# Install Some tools
RUN apk add --no-cache \
  curl \
  bats \
  docker \
  git

# Configure Proxy
RUN mkdir -p /root/.m2
COPY ./settings.xml /root/.m2/settings.xml
----
