
[{invert}]
= Démarrer le lab

== Pré-requis

* VirtualBox (5.1.30+) et Vagrant (2.0.1+)
* Pour le proxy HTTP : https://github.com/tmatilai/vagrant-proxyconf

[source,bash]
----
# Vérifier que vagrant est présent
vagrant -v

# Installer le plugin vagrant
vagrant plugin install vagrant-proxyconf

# Configurer le plugin
export VAGRANT_HTTP_PROXY=http://10.0.4.2:3128
export VAGRANT_HTTPS_PROXY="${VAGRANT_HTTP_PROXY}"
export VAGRANT_NO_PROXY=localhost,127.0.0.1

# Configurer le réseau
export EXTERNAL_PORT=10000
----
// ** et/ou https://github.com/AlbanMontaigu/docker-transparent-proxy

== Obtenir le template de la VM

[source,bash,subs="attributes"]
----
vagrant box add jenkins-lab-demo {box-url}
----

== Initialiser l'environnement

* Créer un dossier de travail nommé `jenkins-lab-demo`
dans votre HOME utilisateur
* Se positionner dans ce dossier
* Exécuter `vagrant init`

[source,bash]
----
mkdir ~/jenkins-lab-demo
cd ~/jenkins-lab-demo
vagrant init -m -f jenkins-lab-demo
----

== Démarrer / Arrêter le lab

[source,bash]
----
vagrant up # Démarrer la VM
vagrant suspend # Suspendre la VM
vagrant resume # Relancer la VM
vagrant halt # Arrêter "proprement la VM"
vagrant destroy # Détruire la VM (BRUTAL)
----

== Accéder au lab

* Dans votre navigateur, ouvrir link:{homepage-url}[{homepage-url},window=_blank]
* Bienvenue sur la page d'accueil du Lab:
** Le lien *Slides* vous permettra d'accéder au slides

== Accéder au code source

* Cliquer sur le lien *Git Server* sur la page d'accueil du Lab
** link:{gitserver-url}[Lien direct,window=_blank]
** *S'authentifier* en tant que *`{admin-user}`* (mot de passe `{admin-password}`)
* Cliquer sur *Explore* (en haut)
** Cliquer sur *{admin-user}/{demoapp-repo-name}*
*** link:{demoapp-repo-web-url}[Lien direct,window=_blank]
